const fieldTemplates = {
    Flight: [
      { key: 'name', type: 'String', required: true, validations: { unique: true } },
      { key: 'price', type: 'BigDecimal', required: false, validations: {} },
      { key: 'flightId', type: 'String', required: true, validations: { unique: true } },
      { key: 'flightNumber', type: 'String', required: true, validations: {} },
      { key: 'origin', type: 'String', required: true, validations: {} },
      { key: 'destination', type: 'String', required: true, validations: {} },
      { key: 'departureDateTime', type: 'ZonedDateTime', required: false, validations: {} },
      { key: 'arrivalDateTime', type: 'ZonedDateTime', required: false, validations: {} },
      { key: 'Duration', type: 'String', required: false, validations: {} },
      { key: 'airport', type: 'String', required: false, validations: {} },
      { key: 'carrier', type: 'String', required: false, validations: {} },
    ],
    Hotel: [
      { key: 'name', type: 'String', required: true, validations: { unique: true } },
      { key: 'price', type: 'Double', required: true, validations: {}, apiDetails: {} },
      { key: 'city', type: 'String', required: true, validations: {} },
      { key: 'address', type: 'String', required: false, validations: {} },
      { key: 'postalCode', type: 'String', required: false, validations: {} },
      { key: 'facilities', type: 'String', required: false, validations: {} },
      { key: 'images', type: 'String', required: false, validations: {} },
      { key: 'guests', type: 'Integer', required: true, validations: {} },
      { key: 'locationId', type: 'String', required: false, validations: {} },
      { key: 'checkInTime', type: 'String', required: false, validations: {} },
      { key: 'checkOutTime', type: 'String', required: false, validations: {} },
      { key: 'description', type: 'String', required: false, validations: {} },
      { key: 'reviews', type: 'String', required: false, validations: {}, apiDetails: { apiUrl: '', headers: [], method: 'GET', payload: '', responseParser: [] } },
    ],
    Room: [
      { key: 'name', type: 'String', required: true, validations: { unique: true } },
      { key: 'price', type: 'Double', required: true, validations: {} },
      { key: 'images', type: 'String', required: false, validations: {} },
      { key: 'guestCount', type: 'Integer', required: true, validations: {} },
      { key: 'size', type: 'String', required: false, validations: {} },
      { key: 'facilities', type: 'String', required: false, validations: {} },
      { key: 'hotelName', type: 'String', required: true, validations: {} },
      { key: 'description', type: 'String', required: false, validations: {} },
    ],
    Addon: [
      { key: 'name', type: 'String', required: true, validations: { unique: true } },
      { key: 'description', type: 'String', required: false, validations: {} },
      { key: 'images', type: 'String', required: false, validations: {} },
      { key: 'destination', type: 'String', required: false, validations: {} },
      { key: 'addOnType', type: 'String', required: false, validations: {} },
      { key: 'price', type: 'Double', required: true, validations: {} },
      { key: 'tags', type: 'String', required: false, validations: {} },
    ],
  
    Bundle: [
      { key: 'name', type: 'String', required: true, validations: { unique: true } },
      { key: 'description', type: 'String', required: false, validations: {} },
      { key: 'origin', type: 'String', required: false, validations: {} },
      { key: 'destination', type: 'String', required: false, validations: {} },
      { key: 'images', type: 'String', required: false, validations: {} },
      { key: 'transport', type: 'String', required: false, validations: {} },
      { key: 'accommodation', type: 'String', required: false, validations: {} },
      { key: 'addOns', type: 'String', required: false, validations: {} },
      { key: 'tags', type: 'String', required: false, validations: {} },
      { key: 'price', type: 'Double', required: false, validations: {} },
      { key: 'date', type: 'ZonedDateTime', required: false, validations: {} },
    ],
    // Add Room, Adon, Bundle templates here as needed
  };
  
  export default fieldTemplates;