import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { SidebarProvider } from "@/context/SidebarContext";
import { JHipsterProvider } from "@/context/JHipsterContext";
// import { SessionProvider } from 'next-auth/react';
import { NextAuthProvider } from "@/pages/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <JHipsterProvider>
          <SidebarProvider>
            <AuthContextProvider>
              <body className={inter.className}>{children}</body>
            </AuthContextProvider>
          </SidebarProvider>
        </JHipsterProvider>
      </NextAuthProvider>
    </html>
  );
}
