import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { SidebarProvider } from "@/context/SidebarContext";
import { JHipsterProvider } from "@/context/JHipsterContext";
import NextAuthProvider from "@/context/provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ReactNode } from "react";
import { ModalProvider } from "@/context/useModal";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: ReactNode;
  params: {
    locale: string;
  };
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const messages = await getMessages();

  const lang = params.locale;

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={lang}>
        <ModalProvider>
          <NextAuthProvider>
            <JHipsterProvider>
              <SidebarProvider>
                <AuthContextProvider>
                  <body className={inter.className}>{children}</body>
                </AuthContextProvider>
              </SidebarProvider>
            </JHipsterProvider>
          </NextAuthProvider>
        </ModalProvider>
      </html>
    </NextIntlClientProvider>
  );
}
