import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { SidebarProvider } from "@/context/SidebarContext";
import { JHipsterProvider } from "@/context/JHipsterContext";
import NextAuthProvider from "@/context/provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const messages = await getMessages();
  
  return (
    <NextIntlClientProvider messages={messages}>
      <html lang="en">
        <NextAuthProvider>
          <JHipsterProvider>
            <SidebarProvider>
              <AuthContextProvider>
                <body className={inter.className}>{children}</body>
              </AuthContextProvider>
            </SidebarProvider>
          </JHipsterProvider>
        </NextAuthProvider>
      </html>
    </NextIntlClientProvider>
  );
}
