import type { Metadata } from "next";
import React, { Suspense } from "react";
import { Inter } from "next/font/google";
// import "../globals.css";
import "./globals.css";
import HeaderManagement from "@/components/Navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <div style={{ backgroundColor: "#ffffff" }} className="flex">
        <div className="min-h-screen">
          <HeaderManagement />
        </div>
        <main className="px-4 sm:px-10 lg:px-12 2xl:mx-auto 2xl:px-0">
          {children}
        </main>
      </div>
    </Suspense>
  );
}


